[package]
name = "advent-2019"
version = "0.1.0"
authors = ["Chris Lieb <clieb@bitsighttech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8.2"
maplit = "1.0.2"
num = "0.2.1"
regex = "1.3.3"
